version: "3.8"

name: moshi

services:

  moshi-rust:
    build:
      context: ./rust
    restart: unless-stopped
    volumes:
      - hf-cache:/root/.cache/huggingface
      - ./rust/tts.toml:/workspace/tts.toml  # Mount config file
    environment:
      - HF_REPO=kyutai/moshiko-pytorch-bf16  #
    ports: 
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
  moshi:
    build:
      context: ./moshi
    restart: unless-stopped
    volumes:
      - hf-cache:/root/.cache/huggingface
    environment:
      #- HF_REPO=kyutai/moshika-pytorch-bf16
      - HF_REPO=kyutai/moshiko-pytorch-bf16
    ports: 
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
    profiles:
      - python

volumes:
  hf-cache:
